# -*- coding: utf-8 -*-
"""221- LAB1 TASK 4.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1SlNXfDgy0ktQD6oBR_YYla3AQbBSrY2J
"""

#TASK 4

inputted_file = open("input4.txt",'r')
A = []
B = []

list= inputted_file.read().split()

for i in range(len(list)):
    if i<(len(list)//2): 
        A.append(list[i].split(","))
    else:
        B.append(list[i].split(","))

def Multiply_matrix(A,B):
    C=[[0]*len(B) for i in range(len(B))]   
    for i in range(0,len(B)):   #O(n)
        for j in range(0,len(B)):   #O(n)
            for k in range(0,len(B)):   #O(n)
                C[i][j] += int(A[i][k]) * int(B[k][j])
    return C
    
output= open("output4.txt", mode= "w")
Final= Multiply_matrix(A,B)


output.write(str(Final))
#output.write("/n")
output.write("\nThe worst case time complexity of the program is O(n^3)")
output.close()

#pseudo code
#Procedure Multiply_matrix(A,B) 
#Input A,B nxn matrix 
#Output C nxn matrix 
#begin 
#Initialize C as a nxn zero matrix 
#for i = 0 to n-1 
#for j = 0 to n-1 
#for k = 0 to n-1 
#C[i,j] += A[i,k]*B[k,j] 
#end for 
#end for 
#end for 
#end Multply_matrix