# -*- coding: utf-8 -*-
"""221- LAB 1 TASK 1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1162PBgg15sgFWGdG5Q0JLlCcfqEoEUi-
"""

#TASK 1

inputted_file = open('input.txt', 'r')
temp = inputted_file.read().split()
output_file = open("output.txt", "w+") #used w+ for writing and reading at a same time

even_parity = 0
odd_parity = 0
no_parity = 0
palin_count = 0
nonpalin_count = 0


def paritycheck(item):

    global even_parity
    global odd_parity
    global no_parity

    #if no dot found then it must be integer 
    if "." in item:
        no_parity += 1
        return f"{item} cannot have parity and"

    convert= int(item)
    if convert % 2 ==0:
        even_parity+= 1
        return f"{item} has even parity and"
    else:
        odd_parity += 1
        return f"{item} has odd parity and"


def isPalindrome(item):


    global palin_count
    global nonpalin_count


    if len(item) <= 0:
        nonpalin_count += 1
        return f"{item} no word found & is not a palindrome\n"

    n = len(item)
    j = 0

    while j< n /2:
        if item[j] != item[n-1-j]: #Pseudocode part
            nonpalin_count +=1
            return f"{item} is not a palindrome\n"
        j += 1
    else:
        palin_count += 1
        return f"{item} is a palindrome\n"




for i in range(len(temp)):
    if i % 2 == 0:
        x = paritycheck(temp[i])
        output_file.write(x)
    else:
        x = isPalindrome(temp[i])
        output_file.write(x)


#recordingTXT part
n = (len(temp) / 2)
odd_parity = (odd_parity / n) * 100
even_parity = (even_parity / n) * 100
no_parity = (no_parity / n) * 100
palin_count = (palin_count / n) * 100
nonpalin_count = (nonpalin_count / n) * 100


record = open("records.txt", "w+")
record.write(f"Percentage of odd parity is: {odd_parity}%\n")
record.write(f"Percentage of even parity is: {even_parity}%\n")
record.write(f"Percentage of no parity is: {no_parity}%\n")
record.write(f"Percentage of palindrome is : {palin_count}%\n")
record.write(f"Percentage of non-palindrome is : {nonpalin_count}%")


isPalindrome(temp)
inputted_file.close()